routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\UserController;

Route::get('/', function() {
	return view('app.login.index');
});

Route::name('admin.')->prefix('admin')->middleware('auth')->group(function () {
    Route::resource('veiculos', VehicleController::class);
    Route::resource('usuarios', UserController::class)->middleware('admin');
});

Route::prefix('/')->group(function () {
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
    Route::post('login', [LoginController::class, 'login']);
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');
});

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Hash;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_admin'
    ];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $guard = [
        'password_confirmation',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Vehicle.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vehicle extends Model
{
    use HasFactory;

    protected $fillable = [
        'brand_id',
        'name',
        'year_manufacture',
        'year_model',
        'number_ports',
        'observation',
    ];

    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('created_at', 'desc')->paginate(5);
        return view('app.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('app.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        User::create($request->all());
        return redirect()->back()->with('success', 'Usuário cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('app.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        User::where('id', $id)->update($request->except(['_token', '_method', 'password_confirmation']));
        return redirect()->back()->with('success', 'Usuário atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        return redirect()->back()->with('success', 'Usuário excluído com sucesso!');
    }
}

app/Http/Controllers/VehicleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Brand;
use App\Models\Vehicle;
use App\Http\Requests\VehicleRequest;
use Illuminate\Http\Request;

class VehicleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vehicles = Vehicle::with('brand:id,name')->paginate(5);
        return view('app.vehicle.index', compact('vehicles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brands = Brand::orderBy('name')->get();
        return view('app.vehicle.create', compact('brands'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VehicleRequest $request)
    {
        Vehicle::create($request->all());
        return redirect()->back()->with('success', 'Veículo cadastrado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $vehicle = Vehicle::find($id);
        return view('app.vehicle.show', compact('vehicle'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vehicle = Vehicle::find($id);
        $brands = Brand::orderBy('name')->get();
        return view('app.vehicle.edit', compact('brands', 'vehicle'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(VehicleRequest $request, $id)
    {
        Vehicle::where('id', $id)->update($request->except(['_token', '_method']));
        return redirect()->back()->with('success', 'Veículo atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Vehicle::destroy($id);
        return redirect()->back()->with('success', 'Veículo excluído com sucesso!');
    }
}

resources/views/app/login/index.blade.php
@extends('layouts.app')
@section('title', 'Login')

@section('content')
  <form class="form-signin mt-5" method="POST" action="{{ route('login') }}">
    @csrf
    
    <h1 class="h3 mb-3 font-weight-normal">Entrar</h1>

    <div>
      <label for="inputEmail" class="sr-only">E-mail</label>
      <input type="email" id="inputEmail" class="form-control @error('email') is-invalid @enderror" 
             placeholder="E-mail" name="email" autofocus
      >
      <label for="inputPassword" class="sr-only">Senha</label>
      <input type="password" id="inputPassword" class="form-control @error('password') is-invalid @enderror"
           placeholder="Senha" name="password">
          @error('email')
            <span class="invalid-feedback mb-2" role="alert">
              <strong>{{ $message }}</strong>
            </span>
          @enderror
          @error('password')
            <span class="invalid-feedback mb-2" role="alert">
              <strong>{{ $message }}</strong>
            </span>
          @enderror
    </div>
      
    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Lembrar-me
      </label>
    </div>
    <button class="btn btn-lg btn-danger btn-block" type="submit">Entrar</button>

    <p class="mt-5 mb-3 text-muted">&copy; 2021</p>
  </form>
@endsection

resources/views/app/users/create.blade.php
@extends('layouts.app')
@section('title', 'Criar novo usuário')


@include('layouts.navbar')

@section('content')
    <div class="container-fluid">

        <div class="col-12 mt-3">
            <h3 class="m-0 p-0">Criar novo usuário</h3>
        </div>

        @include('partials.messages.success')
        @include('partials.messages.errors')

        <div class="col-12">
          <form class="mt-4" method="POST" action="{{ route('admin.usuarios.store') }}">
            @csrf
            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="name">Nome</label>
                <input type="text" class="form-control" name="name" id="name" value="{{ old('name') }}">
                @error('name')
                  <small class="text-danger">{{ $message }}</small>
                @enderror
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-12">
                <label for="email">E-mail</label>
                <input type="email" class="form-control" name="email" id="email" value="{{ old('email') }}">
                @error('email')
                  <small class="text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group col-md-6">
                <label for="password">Senha</label>
                <input type="password" class="form-control" name="password" id="password">
                @error('password')
                  <small class="text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group col-md-6">
                <label for="password-confirmation">Confirmar Senha</label>
                <input type="password" class="form-control" name="password_confirmation" id="password-confirmation">
                @error('password_confirmation')
                  <small class="text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group col-md-6">
                <label for="is-admin">Tipo de usuário</label>
                <select id="is-admin" class="form-control" name="is_admin">
                  <option value="1" {{ old('is_admin') == 1 ? 'selected' : '' }}>Administrador</option>
                  <option value="0" {{ old('is_admin') == 0 ? 'selected' : '' }}>Usuário</option>
                </select>
                @error('is_admin')
                  <small class="text-danger">{{ $message }}</small>
                @enderror
              </div>
            </div>
            <button type="submit" class="btn btn-primary mt-3">Salvar</button>
          </form>
        </div>
    </div>
@endsection

resources/views/app/users/edit.blade.php
@extends('layouts.app')
@section('title', 'Editar usuário')


@include('layouts.navbar')

@section('content')

    <div class="container-fluid">

        <div class="col-12 mt-3">
            <h3 class="m-0 p-0">Editar usuário</h3>
        </div>

        @include('partials.messages.success')
        @include('partials.messages.errors')

        <div class="col-12">
            <form class="mt-4" method="POST" action="{{ route('admin.usuarios.update', $user->id) }}">
                @csrf
                @method('PUT')
                <div class="form-row">
                  <div class="form-group col-md-12">
                    <label for="name">Nome</label>
                    <input type="text" class="form-control" name="name" id="name" value="{{ old('name', $user->name) }}">
                    @error('name')
                      <small class="text-danger">{{ $message }}</small>
                    @enderror
                  </div>
                </div>
                <div class="form-row">
                  <div class="form-group col-md-12">
                    <label for="email">E-mail</label>
                    <input type="email" class="form-control" name="email" id="email" value="{{ old('email', $user->email) }}">
                    @error('email')
                      <small class="text-danger">{{ $message }}</small>
                    @enderror
                  </div>

                  <div class="form-group col-md-6">
                    <label for="password">Senha</label>
                    <input type="password" class="form-control" name="password" id="password">
                    @error('password')
                      <small class="text-danger">{{ $message }}</small>
                    @enderror
                  </div>
                  <div class="form-group col-md-6">
                    <label for="password-confirmation">Confirmar Senha</label>
                    <input type="password" class="form-control" name="password_confirmation" id="password-confirmation">
                    @error('password_confirmation')
                      <small class="text-danger">{{ $message }}</small>
                    @enderror
                  </div>

                  <div class="form-group col-md-6">
                    <label for="is-admin">Tipo de usuário</label>
                    <select id="is-admin" class="form-control" name="is_admin">
                      <option value="1" {{ old('is_admin',  $user->is_admin) == 1 ? 'selected' : '' }}>Administrador</option>
                      <option value="0" {{ old('is_admin',  $user->is_admin) == 0 ? 'selected' : '' }}>Usuário</option>
                    </select>
                    @error('is_admin')
                      <small class="text-danger">{{ $message }}</small>
                    @enderror
                  </div>
                </div>

                <button type="submit" class="btn btn-primary mt-3">Editar</button>
                <a href="{{ route('admin.usuarios.index') }}" class="btn btn-secondary mt-3">Voltar a listagem</a>

              </form>
        </div>

    </div>

@endsection

resources/views/app/users/index.blade.php
@extends('layouts.app')
@section('title', 'Todos os usuário')


@include('layouts.navbar')

@section('content')

    <div class="container-fluid">

        <div class="col-12 mt-3">
            <h3 class="m-0 p-0">Todos os usuários</h3>
        </div>

        <div class="col-12 mt-3">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome</th>
                        <th scope="col">E-mail</th>
                        <th scope="col">Tipo de usuário</th>
                        <th scope="col">Ação</th>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($users as $user)
                        <tr>
                            <th scope="row">{{ $user->id }}</th>
                            <td>{{ $user->name}}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->is_admin == 1 ? "Administrador" : "Usuário" }}</td>
                            <td>
                                <a class="btn btn-sm btn-warning text-white" href="{{ route('admin.usuarios.edit', $user->id) }}">Editar</a>
                                <form action="{{ route('admin.usuarios.destroy', $user->id) }}" class="d-inline" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-danger text-white">Excluir</button>
                                </form>
                            </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                  <div class="mt-4">
                      {!! $users->links() !!}
                  </div>
            </div>
        </div>
    </div>

@endsection

resources/views/app/vehicle/create.blade.php
@extends('layouts.app')
@section('title', 'Registrar veículo')


@include('layouts.navbar')

@section('content')

<div class="container-fluid">

  <div class="col-12 mt-3">
    <h3 class="m-0 p-0">Registrar veículo</h3>
  </div>

  @include('partials.messages.success')
  @include('partials.messages.errors')

  <div class="col-12">
  <form class="mt-4" method="POST" action="{{ route('admin.veiculos.store') }}">
      @csrf
      <div class="form-row">
        <div class="form-group col-md-12">
          <label for="name">Nome do veículo</label>
          <input type="text" class="form-control" name="name" id="name" value="{{ old('name') }}">
          @error('name')
            <small class="text-danger">{{ $message }}</small>
          @enderror
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="year-manufacture">Ano de fabricação</label>
          <input type="text" class="form-control" id="year-manufacture" name="year_manufacture"
                 maxlength="4" value="{{ old('year_manufacture') }}"
          >
          @error('year_manufacture')
            <small class="text-danger">{{ $message }}</small>
          @enderror
        </div>
        <div class="form-group col-md-6">
          <label for="year-model">Ano de modelo</label>
          <input type="text" class="form-control" id="year-model" name="year_model" 
                 maxlength="4" value="{{ old('year_model') }}"
          >
          @error('year_model')
            <small class="text-danger">{{ $message }}</small>
          @enderror
        </div>

        <div class="form-group col-md-12">
          <label for="brand-id">Marca</label>
          <select id="brand-id" name="brand_id" class="form-control">
            @foreach($brands as $brand)
              <option value="{{ $brand->id }}" {{ old('brand_id') == $brand->id ? 'selected' : '' }}>{{ $brand->name }}</option>
            @endforeach
          </select>
          @error('brand_id')
            <small class="text-danger">{{ $message }}</small>
          @enderror
        </div>

        <div class="orm-group col-12 mb-3">
              <label for="number-ports">Número de portas</label> 
              @for($i = 2;$i <= 4;$i++)
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="number_ports" id="{{ $i }}ports" value="{{ $i }}"
                      {{ old('number_ports') == $i ? 'checked' : '' }}
                      {{ $i === 2 && !old('number_ports') ? 'checked' : '' }}
                  >
                  <label class="form-check-label" for="{{ $i }}ports">
                      {{ $i }} portas
                  </label>
                </div>
              @endfor
              <div>
                  @error('number_ports')
                    <small class="text-danger">{{ $message }}</small>
                  @enderror
              </div>
          </div>

          <div class="form-group col-md-12">
              <label for="observation">Observações</label>
              <textarea rows="3" class="form-control " name="observation" id="observation">{{ old('observation') }}</textarea>
              @error('observation')
                <small class="text-danger">{{ $message }}</small>
              @enderror
          </div>
      </div>

      <button type="submit" class="btn btn-primary mt-3">Salvar</button>
    </form>
  </div>

</div>

@endsection

resources/views/app/vehicle/edit.blade.php
@extends('layouts.app')
@section('title', 'Editar veículo')


@include('layouts.navbar')

@section('content')

    <div class="container-fluid">

        <div class="col-12 mt-3">
            <h3 class="m-0 p-0">Editar veículo</h3>
        </div>

        @include('partials.messages.success')
        @include('partials.messages.errors')

        <div class="col-12">
            <form class="mt-4" method="POST" action="{{ route('admin.veiculos.update', $vehicle->id) }}">
                @csrf
                @method('PUT')
                <div class="form-row">
                  <div class="form-group col-md-12">
                    <label for="car">Nome do veículo</label>
                    <input type="text" class="form-control" name="name" id="name" value="{{ old('name', $vehicle->name) }}">
                    @error('name')
                      <small class="text-danger">{{ $message }}</small>
                    @enderror
                  </div>
                </div>
                <div class="form-row">
                  <div class="form-group col-md-6">
                    <label for="Manufacture">Ano de fabricação</label>
                    <input type="text" class="form-control" id="year-manufacture" name="year_manufacture" maxlength="4" 
                           value="{{ old('year_manufacture', $vehicle->year_manufacture) }}"
                    >
                    @error('year_manufacture')
                      <small class="text-danger">{{ $message }}</small>
                    @enderror
                  </div>
                  <div class="form-group col-md-6">
                    <label for="model">Ano de modelo</label>
                    <input type="text" class="form-control" id="year-model" name="year_model" maxlength="4" 
                           value="{{ old('year_model', $vehicle->year_model) }}"
                    >
                    @error('year_model')
                      <small class="text-danger">{{ $message }}</small>
                    @enderror
                  </div>

                  <div class="form-group col-md-12">
                    <label for="brand">Marca</label>
                    <select id="brand-id" name="brand_id" class="form-control">
                      @foreach($brands as $brand)
                        <option value="{{ $brand->id }}" {{ old('brand_id',  $brand->id) == $brand->id ? 'selected' : '' }}>
                          {{ $brand->name }}
                        </option>
                      @endforeach
                    </select>
                    @error('brand_id')
                      <small class="text-danger">{{ $message }}</small>
                    @enderror
                  </div>

                  <div class="orm-group col-12 mb-3">
                        <label for="modelCar">Número de portas</label> 
                        @for($i = 2;$i <= 4;$i++)
                          <div class="form-check">
                            <input class="form-check-input" type="radio" name="number_ports" id="{{ $i }}ports" value="{{ $i }}"   
                                {{ old('number_ports') == $i ? 'checked' : '' }}
                                {{ $vehicle->number_ports === $i && !old('number_ports') ? 'checked' : '' }}
                            >
                            <label class="form-check-label" for="{{ $i }}ports">
                                {{ $i }} portas
                            </label>
                        </div>
                        @endfor
                        <div>
                            @error('number_ports')
                              <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group col-md-12">
                        <label for="observation">Observações</label>
                        <textarea rows="3" class="form-control " name="observation" id="observation">{{ old('observation', $vehicle->observation) }}</textarea>
                        @error('observation')
                          <small class="text-danger">{{ $message }}</small>
                        @enderror
                      </div>
                </div>

                <button type="submit" class="btn btn-primary mt-3">Editar</button>
                <a href="{{ route('admin.veiculos.index') }}" class="btn btn-secondary mt-3">Voltar a listagem de veículos</a>
              </form>
        </div>

    </div>

@endsection

resources/views/app/vehicle/index.blade.php
@extends('layouts.app')
@section('title', 'List all cars')

@include('layouts.navbar')

@section('content')

    <div class="container-fluid">

        <div class="col-12 mt-3">
            <h3 class="m-0 p-0">Todos os veículos</h3>
        </div>
        
        @include('partials.messages.success')

        <div class="col-12 mt-3">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome do veículo</th>
                        <th scope="col">Ano de fabricação</th>
                        <th scope="col">Ano de modelo</th>
                        <th scope="col">Marca</th>
                        <th scope="col">Número de portas</th>
                        <th scope="col">Observações</th>
                        <th scope="col">Ação</th>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach($vehicles as $vehicle)
                        <tr>
                            <th scope="row">{{ $vehicle->id }}</th>
                            <td>{{ $vehicle->name}}</td>
                            <td>{{ $vehicle->year_manufacture }}</td>
                            <td>{{ $vehicle->year_model }}</td>
                            <td>{{ $vehicle->brand->name }}</td>
                            <td>{{ $vehicle->number_ports }}</td>
                            <td>{{ $vehicle->observation }}</td>
                            <td>
                                <a class="btn btn-sm btn-warning text-white" href="{{ route('admin.veiculos.edit', $vehicle->id) }}">Editar</a>
                                <a class="btn btn-sm btn-primary text-white" href="{{ route('admin.veiculos.show', $vehicle->id) }}">Detalhes</a>
                                <form action="{{ route('admin.veiculos.destroy', $vehicle->id) }}" class="d-inline" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-danger text-white">Excluir</button>
                                </form>
                            </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                  <div class="mt-4">
                    {!! $vehicles->links() !!}
                  </div>
            </div>
        </div>
    </div>

@endsection

resources/views/app/vehicle/show.blade.php
@extends('layouts.app')
@section('title', 'Detalhes do veículo')


@include('layouts.navbar')

@section('content')

    <div class="container-fluid">

        <div class="col-12 mt-3">
            <h3 class="m-0 p-0">Detalhes do veículo</h3>
        </div>

        <div class="col-12 mt-3">

            <div class="card">
                <div class="card-body">
                 
                    <h4>{{ $vehicle->name }}</h4>
                    <hr />

                    <p>Abaixo veja as informações detalhadas do veículo</p>

                    <ul>
                        <li><b>Ano de fabricação</b>: {{ $vehicle->year_manufacture }}</li>
                        <li><b>Ano de modelo</b>: {{ $vehicle->year_model }}</li>
                        <li><b>Marca</b>: {{ $vehicle->brand->name }}</li>
                        <li><b>Número de portas</b>:  {{ $vehicle->number_ports }}</li>
                    </ul>

                    <p><b>Observações: </b></p>
                    <p>{{ $vehicle->observation }}</p>

                    <a href="{{ route('admin.veiculos.index') }}" class="btn btn-secondary mt-3">Voltar a listagem de veículos</a>
                </div>
            </div>
        </div>

    </div>

@endsection

resources/views/layouts/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navNavigation" aria-controls="navNavigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navNavigation">
        <a class="navbar-brand" href="#"><img src="{{ asset('mv_logo.png') }}" width="120" alt=""></a>
        <ul class="navbar-nav float-left mr-auto mt-2 mt-lg-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Veículos
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{{ route('admin.veiculos.create') }}">Novo veículo</a>
                  <a class="dropdown-item" href="{{ route('admin.veiculos.index') }}">Listar veículos</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Usuários
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  @if(Auth::user()->is_admin == 1)
                          <a class="dropdown-item" href="{{ route('admin.usuarios.create') }}">Novo usuário</a>
                  @endif
                  <a class="dropdown-item" href="{{ route('admin.usuarios.index') }}">Listar usuários</a>
                </div>
            </li>
            
        </ul>
        <div class="float-right mr-5">
            <strong>{{ Auth::user()->name }} ({{ Auth::user()->is_admin == 1 ? "Administrador" : "Usuário" }})</strong>  | 
            <a href="{{ route('logout') }}" class="px-1"
                    onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                <span class="text-base font-weight-bold">Sair</span>
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </div>
    </div>
</nav>

resources/views/partials/messages/error.blade.php
@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
        <strong>{{ $message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif